package io.github.erabti.patois.ktor

import io.github.erabti.patois.ktor.models.GenericLocaleResolver
import io.github.erabti.patois.ktor.models.PatoisPluginConfiguration
import io.github.erabti.patois.ktor.models.Resolver
import io.github.erabti.patois.models.BaseAppStrings
import io.github.erabti.patois.models.LocaleResolver
import io.ktor.server.application.*
import io.ktor.server.routing.*
import io.ktor.util.*

@PublishedApi
internal fun getResolverAttributeKey(resolver: GenericLocaleResolver) =
    AttributeKey<Resolver>("patois_resolver_${resolver.hashCode()}")

/**
 * Installs the Patois i18n plugin for Ktor server applications.
 *
 * Call this in your application module to enable locale-aware string resolution:
 *
 * ```kotlin
 * fun Application.module() {
 *     installPatoisPlugin(AppStringsResolver) {
 *         defaultLocale = AppLocale.EN
 *     }
 * }
 * ```
 *
 * @param resolver The locale resolver generated by the Patois Gradle plugin.
 * @param block Optional configuration block for the plugin.
 */
fun Application.installPatoisPlugin(
    resolver: GenericLocaleResolver,
    block: PatoisPluginConfiguration.() -> Unit = {},
) {
    pluginOrNull(PatoisPlugin) ?: install(PatoisPlugin)
    val attribute = getResolverAttributeKey(resolver)
    attributes.computeIfAbsent(attribute) {
        val configuration = PatoisPluginConfiguration().apply(block)

        Resolver(
            localeResolver = resolver, config = configuration
        )
    }
}


/**
 * Retrieves the localized strings for the current request based on the resolved locale.
 *
 * Usage in a route handler:
 * ```kotlin
 * get("/hello") {
 *     val strings = call.strings(AppStringsResolver)
 *     call.respondText(strings.greeting)
 * }
 * ```
 *
 * @param resolver The locale resolver to use for string lookup.
 * @return The localized strings instance for the current request's locale.
 * @throws IllegalStateException if the Patois plugin is not installed.
 */
inline fun <reified StringsT : BaseAppStrings> ApplicationCall.strings(resolver: LocaleResolver<StringsT, *>): StringsT {
    val attribute = getResolverAttributeKey(resolver)
    val resolverInstance =
        application.attributes.getOrNull(attribute) ?: error("Patois plugin is not installed with the given resolver")

    return resolverInstance.resolve<StringsT>(this)
}

/**
 * Retrieves the localized strings for the current request. Convenience extension for [RoutingContext].
 *
 * @see ApplicationCall.strings
 */
inline fun <reified StringsT : BaseAppStrings> RoutingContext.strings(resolver: LocaleResolver<StringsT, *>): StringsT {
    return call.strings<StringsT>(resolver)
}


internal val PatoisPlugin = createApplicationPlugin(name = "Patois") {}
